version = "1.4-beta2"
versionCode = 1036
timestamp = 1699337220
channel = "PREVIEW"

[notes.en]
highlights = []
items = [
    "Improvement: improve mediastore refresh (may fix the problem of scaning media in some devices)",
    "Improvement: various minor miscellaneous ui refinement",
]

[notes.zh]
highlights = []
items = [
    "改进 改进 mediastore 刷新 (可能将修复某些设备中扫描媒体的问题)",
    "改进 各种细小用户界面改进",
]