version = "1.4-beta1"
versionCode = 1035
timestamp = 1699157800
channel = "PREVIEW"

[notes.en]
highlights = []
items = [
    "Translation: update Portuguese, Brazilian (by EddieMattos)",
    "Development: upgrade dependencies, cleanup code",
]

[notes.zh]
highlights = []
items = [
    "翻译 更新巴西葡萄牙语(EddieMattos)",
    "开发 更新依赖, 清理代码",
]