version = "1.4.0"
versionCode = 1040
timestamp = 1697446000
channel = "STABLE"

[notes.en]
highlights = []
items = [
    "New: customizable list item layout style with more options",
    "Fix: spamming error notifications after devices rebooting (merely mute)",
    "Improvement: Dark/Light Mode would be switched after system dark mode changed instantly without closeing and reopening the app",
    "Improvement: add Shuffle Mode and Repeat Mode buttons in Notification (since Android T) and Android Auto",
    "Improvement: display album artwork in Android Auto (basic support)",
    "Improvement: improve mediastore refresh (may fix the problem of scaning media in some devices)",
    "Improvement: various minor miscellaneous ui refinements",
    "Modify: replace some icons",
    "Modify: show song order instead of images in Playlist Detail",
    "Translation: update Finnish (by Latzze)",
    "Translation: update Arabic (by Yrando)",
    "Translation: update Portuguese, Brazilian (by EddieMattos)",
    "Translation: update Japanese (by aorinngoDo)",
    "Translation: update Turkish (by evladifatihan)",
    "Modify: forbid upgrading from v0.3.4 and older",
    "Modify: warn when upgrading from v0.7.1 and older",
    "Development: use webp and svg formats in assets and resources to shrink artifacts size",
    "Development: upgrade dependencies, cleanup code",
]

[notes.zh]
highlights = []
items = [
    "新增 可定制列表项样式",
    "修复 设备重启后出现的大量错误通知(仅屏蔽)",
    "改进 深色模式在系统深色模式改变后立即更改而无需重进",
    "改进 在通知(Android T 及以上)和 Android Auto 中, 添加随机模式和重复模式按钮",
    "改进 在 Android Auto 中, 显示专辑封面 (仅基本支持)",
    "改进 改进 mediastore 刷新 (可能将修复某些设备中扫描媒体的问题)",
    "改进 各种细小用户界面改进",
    "修改 替换部分图标",
    "修改 在 播放列表详情 中, 显示歌曲顺序而非图片",
    "翻译 更新 芬兰语 (Latzze)",
    "翻译 更新 阿拉伯语 (Yrando)",
    "翻译 更新 巴西葡萄牙语 (EddieMattos)",
    "翻译 更新 日语 (aorinngoDo)",
    "翻译 更新 土耳其语 (evladifatihan)",
    "修改 禁止从 v0.3.4 之前的版本升级至当前版本",
    "修改 警告从 v0.7.1 之前的版本升级至当前版本",
    "开发 使用 webp 和 svg 格式以减少大小",
    "开发 更新依赖, 清理代码",
]