name: dev
on:
  push:
    branches:
      - 'dev'
      - 'main'
    tags-ignore:
      - 'v*'
      - 'preview_*'
      - 'test*'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'
      - 'tools/**'
      - 'fdroid.properties'
      - '*.json'
      - '**.md'
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'
      - 'main'
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - 'crowdin.yml'
      - 'fastlane/metadata/android/**'
      - 'tools/**'
      - 'fdroid.properties'
      - '*.json'
      - '**.md'

jobs:
  build:
    name: Build Dev CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare Gradlew
        # just download gradle wrapper, start gradle daemon and prepare composing builds, make actual build logs clean
        run: |
          ./gradlew


      - name: Generate Sign Config
        env:
          SECRETS_KEY: ${{ secrets.KEY }}
          SECRETS_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          SECRETS_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SECRETS_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_FILE: ${{ github.workspace }}/key.jdk
          CONFIG_FILE: ${{ github.workspace }}/signing.properties
        run: |
          bash ${{ github.workspace }}/scripts/generate_signing_key.sh


      - name: Build with Gradle (Assemble CheckoutDebug)
        run: |
          ./gradlew assembleCheckoutDebug --stacktrace --parallel

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: dev
          path: ./app/build/outputs/apk/*/debug/*.apk
          retention-days: 3

