name: lts_release
on:
  push:
    tags:
      - "v0.0.*"
    paths-ignore:
      - "README.md"
      - "version"
      - "version.json"

jobs:
  build:
    name: build ltsb release
    runs-on: ubuntu-18.04
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0

      # - uses: gradle/wrapper-validation-action@v1 # its timeout fails the action

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Create DX links for BuildTools
        run: ln -s $ANDROID_HOME/build-tools/31.0.0/d8 $ANDROID_HOME/build-tools/31.0.0/dx && ln -s $ANDROID_HOME/build-tools/31.0.0/lib/d8.jar $ANDROID_HOME/build-tools/31.0.0/lib/dx.jar
        # we are using Android Gradle Plugin 4.x.x, which can not find 'dx' in SDK31


      - name: Build with Gradle
        run: ./gradlew buildRelease --stacktrace

      - name: signing apk
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: 30.0.3
        with:
          releaseDirectory: ./app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ltsb_release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Upload mapping.txt
        uses: actions/upload-artifact@v2
        with:
          name: mapping
          path: "app/build/outputs/mapping/release/mapping.txt"

      - name: Release New Version
        uses: softprops/action-gh-release@v1
        id: release_github

        if: startsWith(github.ref, 'refs/tags/v0.0')
        with:
          name: "[LTS] ${{ github.ref_name }}"
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            ${{ github.workspace }}/app/build/outputs/mapping/release/mapping.txt
          prerelease: false
          draft: true
          tag_name: ${{ github.ref }}
          body: CI LTS Release - ${{ github.ref }}
          body_path: ${{ github.workspace }}/ReleaseNote.md
          token: ${{ secrets.TOKEN }}

      - name: Upload to TG
        uses: appleboy/telegram-action@master

        if: startsWith(github.ref, 'refs/tags/v0.0')
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            <b>LTS Version!</b>
            <b>${{ github.ref_name }}</b> (<pre>${{ github.sha }}</pre>)
            This is Long Term Support version release!

            <b>LTS版本更新!</b>
            长期支持版

            <a href="https://github.com/chr56/Phonograph_Plus/releases/tag/${{ github.ref_name }}"> GitHub Link </a>
            <pre>${{ github.action_path }}</pre>
          format: html
          document: ${{ github.workspace }}/${{steps.sign_app.outputs.signedReleaseFile}}
          disable_notification: true
          disable_web_page_preview: true
